### PR TITLE
Deepsource cleanup

### PR DESCRIPTION
**Pull request by kevinhu**
- Reorganized and revised documentation for clarity and ease of setup.
- Fixed a bunch of Pylint+DeepSource warnings.

### CODE REVIEW

**Comment by avgupta456** [comment]
Thanks for tagging me, deepsource looks really cool! I'll check it out tomorrow

**Review by avgupta456 — APPROVED** [review]
Looks good to me

**Comment by avgupta456** [comment]
Do you know why the Deepsource Python check failed?

**Comment by kevinhu** [comment]
Not sure – it looks like the run has stalled on their end: https://deepsource.io/gh/coursetable/ferry/run/66927a26-0d14-41ff-9085-fd93074da362/python. I'll try a test push to restart it.

**Pull request merged**
